---

- name: Mac Fonts | Set fonts variable
  set_fact:
    fonts:
      - name: FiraCode
        archive: https://github.com/tonsky/FiraCode/archive/master.tar.gz
        directory: distr/ttf
        files:
          - FiraCode-Bold.ttf
          - FiraCode-Light.ttf
          - FiraCode-Medium.ttf
          - FiraCode-Regular.ttf
          - FiraCode-Retina.ttf
      - name: Monoid
        archive: https://github.com/JB-Dmitry/monoid/archive/master.tar.gz
        directory: Monoisome
        files:
          - Monoisome-Regular.ttf
  when: fonts is undefined

- name: Mac Fonts | Download fonts
  get_url:
    url: "{{ item.archive }}"
    dest: "/tmp/fonts-{{ item.name }}.tar.gz"
  with_items: "{{ fonts }}"

- name: Mac Fonts | Make sure extraction folders exist
  file:
    path: "/tmp/fonts-{{ item.name }}/"
    state: directory
  with_items: "{{ fonts }}"

- name: Mac Fonts | Extract fonts
  unarchive:
    src: "/tmp/fonts-{{ item.name }}.tar.gz"
    dest: "/tmp/fonts-{{ item.name }}"
    remote_src: yes
  with_items: "{{ fonts }}"

- name: Mac Fonts | Install fonts
  copy:
    src: "/tmp/fonts-{{ item.0.name }}/{{ item.0.name }}-master/{{ item.0.directory }}/{{ item.1 }}"
    dest: "/Users/KarlHepworth/Library/Fonts/{{ item.1 }}"
  with_subelements:
    - "{{ fonts }}"
    - "files"